import React, { useEffect, useState, useMemo } from 'react';
import ReactDOM from 'react-dom';

import { useRouter } from 'next/router';
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css'
import '../assets/styles/app.scss'
import '../styles/globals.css'
import { UserContext } from '../context/UserContext';
import { SocketContext, socket } from '../context/socket';
import { isAuthenticated, logoutUser } from '../services/auth.service';

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const [user, setUser] = useState(null);
  useEffect(() => {
    // registerRouterEvents();
    // fetchSize();
    // checkAuth();
    // fetchConfig();
  }, []);

  const registerRouterEvents = () => {
    router.events.on('routeChangeStart', (url) => {
      Notiflix.Loading.pulse('Loading...');
    });
    router.events.on('routeChangeComplete', () => {
      Notiflix.Loading.remove();
    });
    router.events.on('routeChangeError', () => {
      Notiflix.Loading.remove();
    });
  };

  const logout = () => {
    logoutUser();
    setUser(null);
    router.push('/');
  };

  const checkAuth = () => {
    const user = isAuthenticated();
    setUser(user);
    if (user) {
      return true;
    }
    return false;
  };
  const providerValue = useMemo(() => ({ user, setUser, checkAuth, logout }), [
    user,
    setUser,
  ]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SocketContext.Provider value={socket}>
        <UserContext.Provider value={providerValue}>
          <Component {...pageProps} />
        </UserContext.Provider>
      </SocketContext.Provider>
      <footer>

      </footer>
    </>
  );
}

export default MyApp
